<?php

namespace AppBundle\Repository;

/**
 * StudijRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudijRepository extends \Doctrine\ORM\EntityRepository
{
}
